### PR TITLE
"The Events Calendar" plugin integration

### PR DESCRIPTION
**Pull request by ryanlebreton-gmu**
This installs the template and CSS override files for integrating the "The Events Calendar" plugin with the Mason theme. Most, if not all of the classes are named very specifically, so I don't anticipate any conflicts, but I'd appreciate some additional eyes on it. The "events-calendar" branch is up-to-date with master as of the morning of 3/16, so you could pull that branch down and install it on test sites if you want. 

Please note that the "default stylesheet used for events templates" option should be set to "Skeleton Styles" in the Display tab of the calendar plugin settings. I believe it's set to the other option out of the box. 

Let me know if you have any thoughts or questions.

### CODE REVIEW

**Comment by jmacario-gmu** [comment]
Ryan:

Thanks for this!
Upon initial review all looks good.

I will test this on some sites in the coming days. 
I am curious what you needed to do/override in the default template files?

Thanks,
Jan

**Comment by ryanlebreton-gmu** [comment]
Hi Jan - I had to make some changes to get the markup of the event detail page to match our single post/page template more closely (e.g. get the main heading into the tan background, add breadcrumbs, etc).

-Ryan

________________________________

**Comment by jmacario-gmu** [comment]
Thanks. Yes I see that that. It looks good and makes a big difference.

So I installed The Events Calendar plugin on my sandbox site (https://jmsandboxgmu.wpengine.com/) to test, and I have a few outstanding issues/questions:

- I added the "Events List" widget to the homepage top widget area to show a list of the upcoming events and I added a title in the widget. It looks like widget title styling on the front-end could use some revision. Example: https://jmsandboxgmu.wpengine.com/ - "Upcoming Events"
 
- I'm not sure what's up with this: I'm getting an error on my sandbox site when viewing the event details page, but only when using your revised template files: "Deprecated: tribe_get_view is deprecated since version 5.13.0! Use On version 6.0.0 this function will be removed. Please refer to https://evnt.is/v1-removal for template customization assistance. instead. in /nas/content/live/jmsandboxgmu/wp-includes/functions.php on line 5316". But this error does not appear on your sandbox site. Example: https://jmsandboxgmu.wpengine.com/event/test-event-1/

- On my test event. I filled in lots of the available fields when creating the event, including info about the event, the venue, and the organizers. This information appears in 3 columns below the event description on the event details page ("details", "organizer", "venue"). I'm seeing some layout issues with this bottom event content: it's all squished. Example: https://jmsandboxgmu.wpengine.com/event/test-event-1/

- Lastly, event images appear twice on event details page: at the top as the featured image for the post, and within the content as the event image. This is certainly more a matter of style, but since the event image also appears large (presumably as long as a large-enough image is used) I think having both the feature image and the event image is duplicative. I would suggest hiding the large top featured image in this template as having just the event image. Thoughts?

Thanks!
Jan

**Comment by ryanlebreton-gmu** [comment]
@jmacario-gmu I think I've addressed all of the issues you found, so this should be ready for another look.

**Comment by jmacario-gmu** [comment]
@ryanlebreton-gmu This looks fantastic! Thanks for implementing these changes.

I just have one more question: 
What is up with the giant SVG image on this test event details page: https://jmsandboxgmu.wpengine.com/event/test-event-1/
Were you getting this on your test site?

If we can get this final issue figured out, I think we're otherwise ready to merge this PR.

Thanks,
Jan

**Comment by ryanlebreton-gmu** [comment]
@jmacario-gmu the giant SVG issue should be resolved. Let me know if you still see it, or if you happen to catch anything else.

**Comment by jmacario-gmu** [comment]
@ryanlebreton-gmu This looks great! Thanks for your work on this. This will be a nice new feature.

I did see one minor thing, but I don't think it should stop us from merging this PR and pushing out this change as a new theme version to get this feature out there. When you click the "Add to Calendar" button it expands the div below to provide the options for which calendar to add the event to, but when you click it again, it doesn't collapse (although the arrow icon in the button makes it appear that it should). Again, I don't think this should stop us from moving forward with it but I mention it for when you have a chance to look at it.

Thanks again!

**Comment by ryanlebreton-gmu** [comment]
I've noticed that too. I've found that I can close it by clicking to the left, right, above or below it, but for whatever reason, clicking right on it doesn't work. I'm not sure if it's a glitch in the plugin or something in the way I've styled it, but I'll keep it in mind. Thanks!
________________________________

**Comment by ryanlebreton-gmu** [comment]
Thanks, this is good feedback. That deprecated warning is particularly mysterious. I initially thought I might be running an outdated version of the calendar on my test site, which was technically true, but it was still higher than 5.13 (and going from 5.14.0 to 5.14.1 didn't raise that warning). I'll spend some time with this and get back to you when I have an update.

-R

________________________________

**Pull request merged**
