### PR TITLE
Add CSS to make WYSIWYG editor (classic) match the Mason theme.

### PR DESCRIPTION
**Pull request by ryanlebreton-gmu**
@jmacario-gmu - I thought it might be nice to have the WYSIWYG editor match the client view a bit more closely since it's currently inheriting its colors from the twentytwenty theme. This should do that for the classic editor. Can you give it a try?

### CODE REVIEW

**Comment by jmacario-gmu** [comment]
@ryanlebreton-gmu This is a good improvement. Of course we should implement. 

I have a couple questions/requests:

First, the font-size in the editor seems quite large. I would suggest something like 16px instead. Thoughts?

Second, instead of adding it directly to the functions.php file, can we put your added code inside an include file, like the other modules in the functions.php file. I believe it's a trivial amount of extra effort for the server to assemble those php files at runtime, and helps to keep the functions.php organized and the code modular, rather than the functions.php file getting too large and hard to comprehend.

Thanks,
Jan

**Comment by ryanlebreton-gmu** [comment]
Those are good suggestions. I'll work on that and add something similar for the block editor.
________________________________

**Comment by ryanlebreton-gmu** [comment]
@jmacario-gmu the new commits address the font size issues and add a stylesheet for the block editor. I also moved the calls into their own include to keep functions.php tidier. Let me know what you think.

**Comment by jmacario-gmu** [comment]
This looks great! Thanks for making those changes. I think we should definitely implement. I'll go ahead and merge this PR.

**Pull request merged**
